<?php

namespace App\Repositories;

use App\Models\Student;

class StudentRepository extends ModelRepository
{
    protected DocumentRepository $documentRepository;
    public function __construct(DocumentRepository $documentRepository)
    {
        $this->documentRepository = $documentRepository;
        parent::__construct();
    }

    public function getModel()
    {
        return Student::class;
    }

    public function getRules()
    {
       return [
           'add' => [
               'name' => 'required|max:255',
               'birth_day' => 'required',
           ],
           'edit' => [
               'name' => 'required|max:255',
               'birth_day' => 'required',
           ]
       ];
    }

    public function create(array $attributes)
    {
        $item = $this->_model->create($attributes);
        $item->documents()->create(['url' => 'hehe']);
        return $item; // TODO: Change the autogenerated stub
    }

    public function resources($id) {
        $result = [
            'validation' => $this->getRules(),
        ];
        if($id) {
            $item = $this->_model->with(['documents'])->find($id);
            $result['object'] = $item;
        }
        return $result;
    }
}
